# Generated by Django 5.2.3 on 2025-06-21 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Custominterviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('post', models.TextField()),
                ('experience', models.CharField(max_length=10)),
                ('submissionDeadline', models.DateTimeField()),
                ('questions', models.TextField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('DSA', models.IntegerField(blank=True, null=True)),
                ('Dev', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('resume', models.FileField(blank=True, null=True, upload_to='./resume')),
                ('attempted', models.BooleanField(default=False)),
                ('isCheated', models.BooleanField(default=False)),
                ('extratedResume', models.TextField(blank=True, null=True)),
                ('virtualResume', models.TextField(blank=True, null=True)),
                ('standardized_resume', models.FileField(blank=True, null=True, upload_to='std_resumes/')),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.custominterviews')),
            ],
        ),
        migrations.CreateModel(
            name='Customconversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.IntegerField(blank=True, null=True)),
                ('Application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.application')),
            ],
        ),
        migrations.CreateModel(
            name='Customquestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='user', max_length=100)),
                ('question', models.TextField(default='Default question text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('convo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.customconversation')),
            ],
        ),
        migrations.CreateModel(
            name='leaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.application')),
            ],
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('Description', models.TextField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='custominterviews',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.CreateModel(
            name='postings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('post', models.TextField()),
                ('experience', models.CharField(max_length=10)),
                ('deadline', models.DateTimeField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='resumeconvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('Application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.application')),
            ],
        ),
        migrations.CreateModel(
            name='resquestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='user', max_length=100)),
                ('question', models.TextField(default='Default question text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('convo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.resumeconvo')),
            ],
        ),
    ]
