# Generated by Django 5.2.3 on 2025-07-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
