# Generated by Django 5.2.3 on 2025-07-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='interview',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resumeconvo',
            name='Application',
        ),
        migrations.RemoveField(
            model_name='customconversation',
            name='Application',
        ),
        migrations.RemoveField(
            model_name='customquestions',
            name='convo',
        ),
        migrations.RemoveField(
            model_name='custominterviews',
            name='org',
        ),
        migrations.RemoveField(
            model_name='postings',
            name='org',
        ),
        migrations.RemoveField(
            model_name='resquestions',
            name='convo',
        ),
        migrations.DeleteModel(
            name='leaderBoard',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Customconversation',
        ),
        migrations.DeleteModel(
            name='Customquestions',
        ),
        migrations.DeleteModel(
            name='Custominterviews',
        ),
        migrations.DeleteModel(
            name='postings',
        ),
        migrations.DeleteModel(
            name='resquestions',
        ),
        migrations.DeleteModel(
            name='resumeconvo',
        ),
    ]
