# Generated by Django 5.2.3 on 2025-07-08 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_customquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='attempted',
        ),
        migrations.RemoveField(
            model_name='application',
            name='isCheated',
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Customquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.customquestion')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interaction')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('cheated', 'cheated')], default='scheduled', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.application')),
            ],
        ),
        migrations.AddField(
            model_name='interaction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interviewsession'),
        ),
    ]
