# Generated by Django 5.2.3 on 2025-07-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_remove_application_attempted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
    ]
