# Generated by Django 5.2.3 on 2025-07-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interviewsession_current_question_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='standardized_resume',
        ),
        migrations.RemoveField(
            model_name='application',
            name='virtualResume',
        ),
        migrations.AddField(
            model_name='application',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='final_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='recommendation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
