# Generated by Django 5.2.3 on 2025-07-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_remove_application_standardized_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
