# Generated by Django 5.2.3 on 2025-07-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_interaction_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
