# Generated by Django 5.2.3 on 2025-07-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_alter_interaction_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='Score',
            field=models.FloatField(),
        ),
    ]
