# Generated by Django 5.2.3 on 2025-07-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_alter_application_score_alter_interviewsession_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='final_feedback',
        ),
    ]
