# Generated by Django 5.2.3 on 2025-07-11 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_remove_interviewsession_final_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customquestion',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.custominterviews'),
        ),
        migrations.AlterField(
            model_name='dsatopics',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsa_topics', to='interview.custominterviews'),
        ),
    ]
