# Generated by Django 5.2.3 on 2025-07-12 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_alter_customquestion_interview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='interview.custominterviews'),
        ),
    ]
