# Generated by Django 5.2.3 on 2025-07-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0012_alter_application_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
