# Generated by Django 5.2.3 on 2025-07-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0014_customquestion_type_alter_interviewsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customquestion',
            name='type',
            field=models.CharField(choices=[('resume', 'resume'), ('interview', 'interview')], default='interview', max_length=20),
        ),
    ]
