# Generated by Django 5.2.3 on 2025-07-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0015_alter_customquestion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='shortlisting_decision',
            field=models.CharField(choices=[('shortlist', 'Shortlist'), ('reject', 'Reject')], default='reject', max_length=20),
        ),
    ]
