# Generated by Django 5.2.3 on 2025-07-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0016_application_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='shortlisting_decision',
            field=models.BooleanField(default=False),
        ),
    ]
