# Generated by Django 5.2.3 on 2025-07-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0018_alter_leaderboard_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='Application',
            new_name='application',
        ),
    ]
