# Generated by Django 5.2.3 on 2025-07-25 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0019_rename_application_leaderboard_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupquestions',
            name='Interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction', to='interview.interaction'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='interview.interviewsession'),
        ),
    ]
