# Generated by Django 5.2.3 on 2025-08-09 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0020_alter_followupquestions_interaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSAInteractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsa_interactions', to='interview.interaction')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.dsatopics')),
            ],
        ),
    ]
