# Generated by Django 5.2.3 on 2025-08-09 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0021_dsainteractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsainteractions',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dsa_topics', to='interview.dsatopics'),
        ),
        migrations.AlterField(
            model_name='dsainteractions',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
