# Generated by Django 5.2.3 on 2025-08-09 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0022_dsainteractions_topic_alter_dsainteractions_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsainteractions',
            name='interaction',
        ),
        migrations.AddField(
            model_name='dsainteractions',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dsa_sessions', to='interview.interviewsession'),
        ),
    ]
