# Generated by Django 5.2.5 on 2025-08-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0023_remove_dsainteractions_interaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='github_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
