# Generated by Django 5.2.5 on 2025-09-03 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0024_application_github_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeconvo',
            name='Application',
        ),
        migrations.RemoveField(
            model_name='resumeconvo',
            name='time',
        ),
        migrations.AddField(
            model_name='resumeconvo',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeconvo',
            name='expected_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeconvo',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeconvo',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeconvo',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_session', to='interview.interviewsession'),
        ),
        migrations.DeleteModel(
            name='resquestions',
        ),
    ]
