# Generated by Django 5.2.5 on 2025-09-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0025_remove_resumeconvo_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeconvo',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
