# Generated by Django 5.2.5 on 2025-09-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0026_resumeconvo_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewsession',
            old_name='score',
            new_name='Devscore',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='DsaScore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='Resumescore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='confidenceScore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
