# Generated by Django 5.2.5 on 2025-09-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0027_rename_score_interviewsession_devscore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='overallScore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
