# Generated by Django 5.2.5 on 2025-09-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0028_interviewsession_overallscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rawResume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
