# Generated by Django 5.2.5 on 2025-10-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0029_application_rawresume'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sesssion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='interview.interviewsession')),
            ],
        ),
    ]
