# Generated by Django 5.2.5 on 2025-12-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0030_interviewimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='final_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='final_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
