# Generated by Django 5.2.5 on 2026-01-05 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0031_application_final_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominterviews',
            name='has_coding_round',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_questions', to='interview.custominterviews')),
            ],
        ),
        migrations.CreateModel(
            name='CodingInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('assistance_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_sessions', to='interview.interviewsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.codingquestion')),
            ],
        ),
    ]
