# Generated by Django 5.2.5 on 2026-01-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0032_custominterviews_has_coding_round_codingquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codinginteraction',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='CodingScore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
