# Generated by Django 5.2.5 on 2026-01-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0033_codinginteraction_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="codinginteraction",
            name="generated_question",
            field=models.TextField(blank=True, null=True),
        ),
    ]
