version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  taskiq_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.taskiq
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - api

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  piston:
    image: ghcr.io/engineer-man/piston
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - piston_data:/piston
    restart: always

volumes:
  redis_data:
  piston_data:
