# Generated by Django 5.2.5 on 2025-12-29 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('course', 'Online Course'), ('tutorial', 'Tutorial'), ('project', 'Project'), ('book', 'Book'), ('article', 'Article'), ('video', 'Video'), ('practice', 'Practice Problems')], max_length=20)),
                ('skill_tags', models.JSONField(default=list)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('duration_hours', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('coursera', 'Coursera'), ('udemy', 'Udemy'), ('youtube', 'YouTube'), ('leetcode', 'LeetCode'), ('github', 'GitHub'), ('medium', 'Medium'), ('official_docs', 'Official Docs'), ('other', 'Other')], max_length=50)),
                ('is_free', models.BooleanField(default=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Learning Resource',
                'verbose_name_plural': 'Learning Resources',
            },
        ),
        migrations.CreateModel(
            name='LearningRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=100)),
                ('current_readiness_score', models.FloatField(default=0)),
                ('target_readiness_score', models.FloatField(default=80)),
                ('milestones', models.JSONField(default=list)),
                ('skill_gaps', models.JSONField(default=list)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('estimated_duration_weeks', models.IntegerField(default=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Roadmap',
                'verbose_name_plural': 'Learning Roadmaps',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_category', models.CharField(max_length=100)),
                ('trend_data', models.JSONField()),
                ('region', models.CharField(default='global', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('ai_generated', 'AI Generated'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor')], default='ai_generated', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Market Trend',
                'verbose_name_plural': 'Market Trends',
                'unique_together': {('skill_category', 'region', 'source')},
            },
        ),
        migrations.CreateModel(
            name='RoadmapProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_index', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career.learningresource')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='career.learningroadmap')),
            ],
            options={
                'verbose_name': 'Roadmap Progress',
                'verbose_name_plural': 'Roadmap Progress Records',
            },
        ),
        migrations.CreateModel(
            name='UserSkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(default=list)),
                ('interests', models.JSONField(default=list)),
                ('target_roles', models.JSONField(default=list)),
                ('experience_years', models.IntegerField(default=0)),
                ('education', models.JSONField(default=dict)),
                ('certifications', models.JSONField(default=list)),
                ('github_username', models.CharField(blank=True, max_length=100, null=True)),
                ('leetcode_username', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('last_profile_scan', models.DateTimeField(blank=True, null=True)),
                ('profile_completeness', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Skill Profile',
                'verbose_name_plural': 'User Skill Profiles',
            },
        ),
    ]
