"""application: replaced approved(bool) to status(str).

Revision ID: 30b8fed6d645
Revises: 737c850a4753
Create Date: 2026-05-09 16:17:58.999684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b8fed6d645'
down_revision: Union[str, Sequence[str], None] = '737c850a4753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('status', sa.String(length=20), nullable=True))
    op.execute("UPDATE applications SET status = 'applied'")
    op.alter_column('applications', 'status', nullable=False)
    op.drop_column('applications', 'approved')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('applications', 'status')
    # ### end Alembic commands ###
