"""Add expected_answer column to resume_questions.

Revision ID: 724ba8de11b6
Revises: c47d76c3b29e
Create Date: 2026-05-21 17:05:57.440201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724ba8de11b6'
down_revision: Union[str, Sequence[str], None] = 'c47d76c3b29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_questions', sa.Column('expected_answer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_questions', 'expected_answer')
    # ### end Alembic commands ###
