"""Make certain fields non nullable.

Revision ID: 737c850a4753
Revises: 5d36ba577387
Create Date: 2026-05-07 16:46:18.775977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737c850a4753'
down_revision: Union[str, Sequence[str], None] = '5d36ba577387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_interviews', 'dsa_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('custom_interviews', 'dev_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('custom_questions', 'expected_answer',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_questions', 'expected_answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('custom_interviews', 'dev_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('custom_interviews', 'dsa_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
