"""Add dsa_question tabel to store dsa questions and added fk to dsa_interaction.

Revision ID: 87a14db23f09
Revises: 30b8fed6d645
Create Date: 2026-05-21 12:58:58.587272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87a14db23f09'
down_revision: Union[str, Sequence[str], None] = '30b8fed6d645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dsa_questions',
    sa.Column('problem_name', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('test_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sample_test_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sample_solution', sa.Text(), nullable=True),
    sa.Column('time_limit_ms', sa.Integer(), nullable=False),
    sa.Column('job_roles', sa.Text(), nullable=True),
    sa.Column('times_served', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsa_questions_difficulty'), 'dsa_questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_dsa_questions_topic'), 'dsa_questions', ['topic'], unique=False)
    op.add_column('dsa_interactions', sa.Column('question_id', sa.Integer(), nullable=True))
    op.add_column('dsa_interactions', sa.Column('language', sa.String(length=50), nullable=True))
    op.create_foreign_key('dsa_interactions_question_id_fkey', 'dsa_interactions', 'dsa_questions', ['question_id'], ['id'], ondelete='SET NULL')
    op.drop_column('dsa_interactions', 'question')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dsa_interactions', sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('dsa_interactions_question_id_fkey', 'dsa_interactions', type_='foreignkey')
    op.drop_column('dsa_interactions', 'language')
    op.drop_column('dsa_interactions', 'question_id')
    op.drop_index(op.f('ix_dsa_questions_topic'), table_name='dsa_questions')
    op.drop_index(op.f('ix_dsa_questions_difficulty'), table_name='dsa_questions')
    op.drop_table('dsa_questions')
    # ### end Alembic commands ###
