"""Add last_heartbeat_at to interview_sessions.

Revision ID: c47d76c3b29e
Revises: 87a14db23f09
Create Date: 2026-05-21 16:05:45.674215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47d76c3b29e'
down_revision: Union[str, Sequence[str], None] = '87a14db23f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('last_heartbeat_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'last_heartbeat_at')
    # ### end Alembic commands ###
