# Generated by Django 5.2.5 on 2025-12-29 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('job', 'Job'), ('internship', 'Internship'), ('hackathon', 'Hackathon'), ('fellowship', 'Fellowship'), ('freelance', 'Freelance')], max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(default=dict)),
                ('responsibilities', models.JSONField(default=list)),
                ('location', models.CharField(max_length=100)),
                ('remote', models.BooleanField(default=False)),
                ('hybrid', models.BooleanField(default=False)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='INR', max_length=10)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (2-5 years)'), ('senior', 'Senior Level (5+ years)'), ('any', 'Any Experience')], default='any', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField()),
                ('source_platform', models.CharField(max_length=50)),
                ('company_logo', models.URLField(blank=True, null=True)),
                ('company_size', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('filled', 'Filled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('match_reasons', models.JSONField(default=list)),
                ('skill_gaps', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('saved', 'Saved'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('priority_rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunity Match',
                'verbose_name_plural': 'Opportunity Matches',
                'ordering': ['-match_score'],
                'unique_together': {('user', 'opportunity')},
            },
        ),
        migrations.CreateModel(
            name='UserApplicationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_apply_enabled', models.BooleanField(default=False)),
                ('min_match_score', models.IntegerField(default=80)),
                ('preferred_opportunity_types', models.JSONField(default=list)),
                ('preferred_locations', models.JSONField(default=list)),
                ('open_to_remote', models.BooleanField(default=True)),
                ('preferred_company_sizes', models.JSONField(default=list)),
                ('excluded_companies', models.JSONField(default=list)),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('max_applications_per_day', models.IntegerField(default=5)),
                ('notification_frequency', models.CharField(default='daily', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Application Preference',
                'verbose_name_plural': 'User Application Preferences',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('drafting', 'Drafting'), ('submitted', 'Submitted'), ('viewed', 'Viewed by Employer'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offer_received', 'Offer Received'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('accepted', 'Offer Accepted')], default='drafting', max_length=30)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume_used', models.URLField(blank=True, null=True)),
                ('auto_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('response_received_at', models.DateTimeField(blank=True, null=True)),
                ('response_content', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opportunities.opportunitymatch')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('user', 'opportunity')},
            },
        ),
        migrations.CreateModel(
            name='SavedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Opportunity',
                'verbose_name_plural': 'Saved Opportunities',
                'unique_together': {('user', 'opportunity')},
            },
        ),
    ]
