# Generated by Django 5.2.5 on 2025-12-29 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview', '0030_interviewimages'),
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('skill_gap', 'Skill Gap'), ('communication', 'Communication Issue'), ('experience', 'Experience Mismatch'), ('technical', 'Technical Weakness'), ('behavioral', 'Behavioral Concern'), ('resume', 'Resume Quality'), ('interview', 'Interview Performance')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('pattern_description', models.TextField()),
                ('occurrences', models.IntegerField(default=1)),
                ('recommended_actions', models.JSONField(default=list)),
                ('related_skills', models.JSONField(default=list)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('addressed', models.BooleanField(default=False)),
                ('addressed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Insight',
                'verbose_name_plural': 'Feedback Insights',
                'ordering': ['-priority', '-occurrences'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('roadmap_update', 'Roadmap Updated'), ('resource_assigned', 'Resource Assigned'), ('mock_interview_scheduled', 'Mock Interview Scheduled'), ('skill_target_updated', 'Skill Target Updated'), ('insight_addressed', 'Insight Addressed')], max_length=30)),
                ('action_description', models.TextField()),
                ('automated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_action_logs', to=settings.AUTH_USER_MODEL)),
                ('insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.feedbackinsight')),
            ],
            options={
                'verbose_name': 'Feedback Action Log',
                'verbose_name_plural': 'Feedback Action Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadinessAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=100)),
                ('overall_readiness_score', models.FloatField()),
                ('skill_scores', models.JSONField(default=dict)),
                ('recommended_improvements', models.JSONField(default=list)),
                ('mock_interviews_completed', models.IntegerField(default=0)),
                ('mock_interview_avg_score', models.FloatField(blank=True, null=True)),
                ('ready_to_apply', models.BooleanField(default=False)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Readiness Assessment',
                'verbose_name_plural': 'Readiness Assessments',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='RejectionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('resume_rejection', 'Resume Rejection'), ('interview_rejection', 'Interview Rejection'), ('offer_declined', 'Offer Declined'), ('application_expired', 'Application Expired')], max_length=30)),
                ('raw_feedback', models.TextField(blank=True)),
                ('ai_analyzed_feedback', models.JSONField(default=dict)),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejection_feedbacks', to='opportunities.application')),
                ('interview_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejection_feedbacks', to='interview.interviewsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rejection Feedback',
                'verbose_name_plural': 'Rejection Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feedbackinsight',
            name='source_feedbacks',
            field=models.ManyToManyField(related_name='insights', to='feedback.rejectionfeedback'),
        ),
        migrations.CreateModel(
            name='SkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('progress_history', models.JSONField(default=list)),
                ('current_score', models.FloatField(default=0)),
                ('current_level', models.CharField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='novice', max_length=20)),
                ('target_level', models.CharField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('target_score', models.FloatField(default=70)),
                ('improvement_rate', models.FloatField(default=0)),
                ('last_assessment_source', models.CharField(blank=True, max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Progress',
                'verbose_name_plural': 'Skill Progress Records',
                'ordering': ['skill'],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
